"""...

Revision ID: 033207338ec3
Revises: a13df239e99a
Create Date: 2026-01-02 16:21:15.137567

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "033207338ec3"
down_revision: str | Sequence[str] | None = "a13df239e99a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
