"""add script stage

Revision ID: 1767c0f40807
Revises: 033207338ec3
Create Date: 2026-01-02 21:30:49.097146
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "1767c0f40807"
down_revision: str | Sequence[str] | None = "033207338ec3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add script stage columns
    op.add_column(
        "jobs",
        sa.Column(
            "script_status",
            sa.Enum("NEW", "READY", "RUNNING", "DONE", "ERROR", name="stagestatus"),
            nullable=False,
            server_default="NEW",
        ),
    )
    op.add_column("jobs", sa.Column("script_lease_owner", sa.String(length=200), nullable=True))
    op.add_column(
        "jobs", sa.Column("script_lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.create_index(op.f("ix_jobs_script_status"), "jobs", ["script_status"], unique=False)

    # Let the application own the default going forward
    op.alter_column("jobs", "script_status", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_script_status"), table_name="jobs")
    op.drop_column("jobs", "script_lease_expires_at")
    op.drop_column("jobs", "script_lease_owner")
    op.drop_column("jobs", "script_status")
    # ### end Alembic commands ###
